import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Trueblue-tree",
  description: "Generated by Trueblue-tree",
};

export default function Layout({ children }: { children: ReactNode }) {
  return <div className="h-full">{children}</div>;
}
